---

- name: Turn off Nextcloud Maintenance Mode
  hosts: all
  become: yes
  tasks:
    - name: Nextcloud Maintenance Mode Off
      ansible.builtin.shell: /home/rootadmin/NextCloudMaintenanceModeOff.sh