---

- name: Turn on Nextcloud Maintenance Mode
  hosts: all
  become: yes
  tasks:
    - name: Nextcloud Maintenance Mode On
      ansible.builtin.shell: /home/rootadmin/NextCloudMaintenanceModeOn.sh